#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/config.star", "get_ca_certificates")

#@ if data.values.ca_cert_data != "":

#@yaml/text-templated-strings
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certificates-binding
  namespace: kpack
  annotations:
    kapp.k14s.io/versioned: ""
type: servicebinding.io/ca-certificates
stringData:
  type: ca-certificates
  #@ i = 0
  #@ for ca_cert in get_ca_certificates():
  certificate_(@= str(i) @): #@ ca_cert
  #@ i += 1
  #@ end

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"kpack-controller"}})
---
spec:
  template:
    spec:
      containers:
        #@overlay/match by="name"
        #@overlay/match-child-defaults missing_ok=True
        - name: controller
          env:
            #@overlay/append
            - name: SERVICE_BINDING_ROOT
              value: "/bindings"
          volumeMounts:
            #@overlay/append
            - mountPath: /bindings/ca-certificates
              name: ca-certificates
      #@overlay/match missing_ok=True
      volumes:
        #@overlay/append
        - name: ca-certificates
          secret:
            secretName: ca-certificates-binding

#@ end
