#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"kpack-controller"}})
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      containers:
        #@overlay/match by="name"
        - name: controller
          env:
          #@ if/end data.values.config.injected_sidecar_support:
          #@overlay/match by="name"
          #@overlay/replace or_add=True
          - name: INJECTED_SIDECAR_SUPPORT
            value: "true"
          #@ if/end data.values.proxy.http_proxy != "":
          - name: HTTP_PROXY
            value: #@ data.values.proxy.http_proxy
          #@ if/end data.values.proxy.https_proxy != "":
          - name: HTTPS_PROXY
            value: #@ data.values.proxy.https_proxy
          #@ if/end data.values.proxy.no_proxy != "":
          - name: NO_PROXY
            value: #@ data.values.proxy.no_proxy
          #@overlay/match missing_ok=True
          resources:
            requests:
              cpu: "20m"
              memory: #@ data.values.controller.resources.requests.memory
            limits:
              memory: #@ data.values.controller.resources.limits.memory
