#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding"}), expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace

#@overlay/match by=overlay.subset({"kind": "RoleBinding"}), expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
