---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-aggregate-app-view
  labels:
    platform.kadras.io/aggregate-to-app-view: "true"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - builders
      - builds
      - images
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-aggregate-app-edit
  labels:
    platform.kadras.io/aggregate-to-app-edit: "true"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - builds
    verbs:
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-aggregate-app-operate
  labels:
    platform.kadras.io/aggregate-to-app-operate: "true"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - builders
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-aggregate-app-view-cluster-access
  labels:
    platform.kadras.io/aggregate-to-app-view-cluster-access: "true"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - clusterbuilders
      - clusterstacks
      - clusterstores
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-aggregate-app-operate-cluster-access
  labels:
    platform.kadras.io/aggregate-to-app-operate-cluster-access: "true"
rules:
  - apiGroups:
      - kpack.io
    resources:
      - clusterbuilders
      - clusterstacks
      - clusterstores
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
      - deletecollection
