#@data/values-schema
#@overlay/match-child-defaults missing_ok=True
---

#@schema/desc "The default repository to use for builder images and dependencies"
#@schema/examples ("Repository on GitHub Container Registry", "ghcr.io/thomasvitale/kpack")
kp_default_repository: ""

#@schema/desc "Configuration for the Secret holding the credentials to access kp_default_repository"
kp_default_repository_secret:
  #@schema/desc "The name of the Secret holding the credentials to access kp_default_repository"
  name: ""
  #@schema/desc "The namespace of the Secret holding the credentials to access kp_default_repository"
  namespace: ""

#@schema/desc "Username to access kp_default_repository. Note: Use _json_key for GCR"
kp_default_repository_username: ""

#@schema/desc "Token to access kp_default_repository. Note: Use contents of service account key json for GCR"
kp_default_repository_password: ""

#@schema/desc "IAM credentials to access kp_default_repository if the registry is on AWS"
kp_default_repository_aws_iam_role_arn: ""

#@schema/desc "Configure proxy support"
proxy:
  #@schema/desc "The HTTPS proxy to use for network traffic"
  https_proxy: ""
  #@schema/desc "The HTTP proxy to use for network traffic"
  http_proxy: ""
  #@schema/desc "A comma-separated list of hostnames, IP addresses, or IP ranges in CIDR format that should not use a proxy"
  no_proxy: ""

#@schema/desc "CA Certificate to be injected into the kpack controller trust store for communicating with self signed registries. Note: This will not be injected into builds, you need to use the cert injection webhook with the kpack.io/build label value"
ca_cert_data: ""
