apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: kpack.packages.kadras.io.0.0.0
spec:
  capacityRequirementsDescription: Container registry with > 1GB available space
  licenses:
  - Apache 2.0
  refName: kpack.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/package-for-kpack/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: kpack.packages.kadras.io
spec:
  categories:
  - build
  displayName: kpack
  longDescription: kpack extends Kubernetes and utilizes unprivileged kubernetes primitives
    to provide builds of OCI images as a platform implementation of Cloud Native Buildpacks
    (CNB).
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: kpack builds application source code into OCI compliant images
    using Cloud Native Buildpacks.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/package-for-kpack
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: kpack
spec:
  packageRef:
    refName: kpack.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
