apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - githubRelease:
      disableAutoChecksumValidation: true
      slug: buildpacks-community/kpack
      tag: v0.11.2
    includePaths:
    - release-*.yaml
    path: .
  path: config/upstream
kind: Config
minimumRequiredVersion: 0.32.0
